// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteTodo struct {
	ID int `json:"id"`
}

type NewTodo struct {
	Text string `json:"text"`
}

type SwitchToggle struct {
	Enable bool `json:"enable"`
}

type User struct {
	UID       string `json:"uid"`
	CreatedAt int    `json:"createdAt"`
	BatchSize *int   `json:"batchSize"`
}
