---
  - block:

    # Nginxのインストール(キーの登録、stable版のリポジトリの登録を含む)
    - name: Install Nginx
      include_tasks: "install_nginx.yml"

    # Nginxの設定(設定ファイルのコピーやパーミッションの確認など)
    - name: Configure Nginx
      include_tasks: "configure_nginx.yml"

    # Nginxの起動
    - name: Start the nginx service
      service:
        name: "{{ nginx_service_name }}"
        state: started
        enabled: yes

    become: yes
