---
- block:
    - name: Install Docker
      shell: "curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh && sudo usermod -aG docker $USER"

    - name: Install Docker Compose
      shell: "sudo curl -L \"https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)\" -o /usr/local/bin/docker-compose"

    - name: Make Docker-Compose Executable
      shell: "sudo chmod +x /usr/local/bin/docker-compose"

  become: yes
